from GraphClass import *

def Create_map_crewmate():
    graph = Graph()
    # We add the node of the graph (14)
    graph.add_node("UE")
    graph.add_node("RE")
    graph.add_node("SE")
    graph.add_node("LE")
    graph.add_node("ME")
    graph.add_node("EL")
    graph.add_node("CA")
    graph.add_node("ST")
    graph.add_node("AD")
    graph.add_node("CO")
    graph.add_node("O2")
    graph.add_node("SH")
    graph.add_node("WE")
    graph.add_node("NA")
    # We add all the edges one time (not in both way) (25)
    graph.add_edge("RE","UE",6.5)
    graph.add_edge("RE","SE",5)
    graph.add_edge("RE","LE",6.5)
    graph.add_edge("UE","LE",7.5)
    graph.add_edge("UE","SE",5.5)
    graph.add_edge("UE","ME",7.5)
    graph.add_edge("SE","LE",6)
    graph.add_edge("LE","EL",8)
    graph.add_edge("LE","ST",10.5)
    graph.add_edge("EL","ST",7)
    graph.add_edge("ST","CO",6)
    graph.add_edge("ST","SH",6)
    graph.add_edge("CO","SH",4)
    graph.add_edge("ST","AD",6.5)
    graph.add_edge("ST","CA",8)
    graph.add_edge("CA","ME",7.5)
    graph.add_edge("UE","CA",10)
    graph.add_edge("CA","AD",7)
    graph.add_edge("CA","WE",6)
    graph.add_edge("WE","O2",7.5)
    graph.add_edge("WE","SH",8.5)
    graph.add_edge("WE","NA",6.5)
    graph.add_edge("O2","NA",1)
    graph.add_edge("O2","SH",8)
    graph.add_edge("SH","NA",8)
    return graph